slam_toolbox:
  ros__parameters:

    # Disable Lifecycle Manager
    use_lifecycle_manager: false

    # Frames
    map_frame: "map"
    odom_frame: "odom"
    base_frame: "base_link"
    scan_topic: "/scan"

    # No real odometry, rely on scan matching
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.0
    minimum_travel_heading: 0.0

    # Map
    resolution: 0.05
    max_laser_range: 4.0
    minimum_time_interval: 0.0

    # Loop closure
    loop_search_maximum_distance: 2.0
    loop_search_minimum_chain_size: 10
    loop_search_maximum_link_distance: 1.0
    do_loop_closing: true

    # Solver
    solver_plugin: "solver_plugins::CeresSolver"
    ceres_linear_solver: "SPARSE_NORMAL_CHOLESKY"
    ceres_preconditioner: "SCHUR_JACOBI"

    # General
    # use_sim_time: false

